jobs:
  run:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./ci/main

name: Build

on:
  schedule:
    - cron: "35 1/3 * * *"
